name: Build Audible RSS
on:
  schedule:
    - cron: "0 9 * * *"  # runs daily at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scrape_audible.py

      # 👇 key fix: ensure gh-pages branch and correct folder
      - name: Deploy feed.xml to Git
